INSERT INTO ROLE(ROLE_ID, DESCRIPTION) VALUES (1, 'Admin');

INSERT INTO ROLE(ROLE_ID, DESCRIPTION) VALUES (2, 'User');

INSERT INTO USER (USER_ID, NAME, PASSWORD, ROLE_ID) VALUES (1, 'admin', '1234', 1);